language: python
python:
  - "3.6"
install:
  - "nvm install node"
  - "nvm use node"
  - "npm install -g eslint@^3.19.0 eslint-plugin-jquery@latest eslint-plugin-jsx-a11y@^5.0.1 eslint-plugin-import@^2.2.0 eslint-plugin-react@^7.0.1 eslint-config-airbnb"
  - "pip install -r requirements.txt"
  - "pip install flake8"
cache: pip
script:
  - flake8
  - python -m unittest discover -p "*_test.py"
  - "eslint ./server/static/js/"
